--SISTEMA DE REDE DE CLINICAS MÉDICAS (SRCM)
--•	Bruno Gonçalves Bezerra
--•	Eduardo Mendes Souza
--•	Emerson Moron Rosa
--•	Letícia Meneses Marques

CREATE TABLE "PESSOA" (
  "cpf" varchar(11) PRIMARY KEY,
  "nome_pessoa" varchar(200) NOT NULL,
  "nome_social" varchar(200),
  "data_nascimento" date NOT NULL,
  "endereco_pessoa" varchar(300),
  "sexo" char(1),
  CONSTRAINT chk_sexo CHECK ("sexo" IN ('M', 'F', 'O'))
);

CREATE TABLE "TELEFONE_PESSOA" (
  "id_telefone_pessoa" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cpf" varchar(11) NOT NULL,
  "telefone" varchar(11) NOT NULL
);

CREATE TABLE "EMAIL_PESSOA" (
  "id_email_pessoa" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cpf" varchar(11) NOT NULL,
  "email" varchar(100) NOT NULL
);

CREATE TABLE "ADMINISTRADOR" (
  "cpf" varchar(11) PRIMARY KEY,
  "matricula_adm" varchar(20) UNIQUE NOT NULL
);

CREATE TABLE "PACIENTE" (
  "id_paciente" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cpf" varchar(11) UNIQUE NOT NULL,
  "prioridade" boolean DEFAULT false
);

CREATE TABLE "FUNCIONARIO" (
  "cpf" varchar(11) PRIMARY KEY,
  "matricula_func" varchar(20) UNIQUE NOT NULL,
  "cargo" varchar(50) NOT NULL,
  "data_admissao" date NOT NULL,
  "status_funcionario" varchar(20) DEFAULT 'ativo',
  CONSTRAINT chk_status_funcionario CHECK ("status_funcionario" IN ('ativo', 'inativo', 'afastado'))
);

CREATE TABLE "ENFERMEIRO" (
  "cpf" varchar(11) PRIMARY KEY,
  "coren" varchar(20) UNIQUE NOT NULL
);

CREATE TABLE "MEDICO" (
  "cpf" varchar(11) PRIMARY KEY,
  "crm" varchar(20) UNIQUE NOT NULL,
  "especialidade" varchar(100),
  "rqe" varchar(20)
);

CREATE TABLE "TEC_RADIOLOGIA" (
  "cpf" varchar(11) PRIMARY KEY,
  "crtr" varchar(20) UNIQUE NOT NULL,
  "atribuicoes" varchar(200)
);

CREATE TABLE "CLINICA" (
  "id_clinica" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome_clinica" varchar(200) NOT NULL,
  "cnpj_clinica" varchar(14) UNIQUE NOT NULL,
  "endereco_clinica" varchar(300) NOT NULL,
  "cpf_administrador" varchar(11)
);

CREATE TABLE "TELEFONE_CLINICA" (
  "id_telefone_clinica" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_clinica" integer NOT NULL,
  "telefone" varchar(15) NOT NULL
);

CREATE TABLE "EMAIL_CLINICA" (
  "id_email_clinica" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_clinica" integer NOT NULL,
  "email" varchar(100) NOT NULL
);

CREATE TABLE "CLINICA_PESSOA" (
  "id_clinica" integer,
  "cpf" varchar(11),
  "data_cadastro" date NOT NULL,
  "cpf_responsavel_cadastro" varchar(11),
  "data_atualizacao" date,
  "status_vinculo" varchar(20) DEFAULT 'ativo',
  PRIMARY KEY ("id_clinica", "cpf"),
  CONSTRAINT chk_status_vinculo_clinica CHECK ("status_vinculo" IN ('ativo', 'inativo'))
);

CREATE TABLE "SERVICO" (
  "id_servico" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome_servico" varchar(200) NOT NULL,
  "valor_base" decimal(10,2) NOT NULL,
  "descricao" text,
  "ativo" boolean DEFAULT true,
  CONSTRAINT chk_valor_base CHECK ("valor_base" >= 0)
);

CREATE TABLE "CONVENIO" (
  "id_convenio" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cnpj_convenio" varchar(14) UNIQUE NOT NULL,
  "nome_convenio" varchar(200) NOT NULL,
  "telefone_convenio" varchar(15),
  "email_convenio" varchar(100),
  "ativo" boolean DEFAULT true
);

CREATE TABLE "COBERTURA" (
  "id_convenio" integer,
  "id_servico" integer,
  "valor_cobertura" decimal(10,2) NOT NULL,
  "limite_utilizacao" varchar(100),
  "requisitos_autorizacao" text,
  "tipo_cobertura" varchar(50),
  "carencia_dias" integer DEFAULT 0,
  PRIMARY KEY ("id_convenio", "id_servico"),
  CONSTRAINT chk_tipo_cobertura CHECK ("tipo_cobertura" IN ('total', 'parcial')),
  CONSTRAINT chk_valor_cobertura CHECK ("valor_cobertura" >= 0),
  CONSTRAINT chk_carencia CHECK ("carencia_dias" >= 0)
);

CREATE TABLE "VINCULO" (
  "id_paciente" integer NOT NULL,
  "id_convenio" integer NOT NULL,
  "numero_cartao" varchar(50) NOT NULL,
  "data_vinculo" date NOT NULL,
  "validade_cartao" date NOT NULL,
  "status_vinculo" varchar(20) DEFAULT 'ativo',
  "data_cancelamento" date,
  PRIMARY KEY ("id_paciente", "id_convenio"),
  CONSTRAINT chk_status_vinculo CHECK ("status_vinculo" IN ('ativo', 'inativo', 'suspenso')),
  CONSTRAINT chk_validade CHECK ("validade_cartao" >= "data_vinculo")
);

CREATE TABLE "AGENDAMENTO" (
  "id_agendamento" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_paciente" integer NOT NULL,
  "cpf_funcionario" varchar(11) NOT NULL,
  "id_clinica" integer NOT NULL,
  "id_convenio" integer,
  "status_agendamento" varchar(20) NOT NULL,
  "data_hora_prevista" timestamp NOT NULL,
  "tipo_agendamento" varchar(30) NOT NULL,
  "faltou" boolean DEFAULT false,
  "status_pagamento" varchar(20),
  "forma_pagamento" varchar(30),
  CONSTRAINT chk_status_agendamento CHECK ("status_agendamento" IN ('agendado', 'confirmado', 'cancelado', 'realizado')),
  CONSTRAINT chk_tipo_agendamento CHECK ("tipo_agendamento" IN ('triagem', 'consulta', 'exame')),
  CONSTRAINT chk_status_pagamento CHECK ("status_pagamento" IN ('pendente', 'pago', 'parcial'))
);

CREATE TABLE "ITEM" (
  "id_agendamento" integer NOT NULL,
  "id_servico" integer NOT NULL,
  "valor_paciente" decimal(10,2) NOT NULL,
  "valor_convenio" decimal(10,2) DEFAULT 0,
  PRIMARY KEY ("id_agendamento", "id_servico"),
  CONSTRAINT chk_valor_paciente CHECK ("valor_paciente" >= 0),
  CONSTRAINT chk_valor_convenio CHECK ("valor_convenio" >= 0)
);

CREATE TABLE "ATENDIMENTO" (
  "id_atendimento" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_agendamento" integer UNIQUE NOT NULL,
  "id_paciente" integer NOT NULL,
  "data_hora_atendimento" timestamp NOT NULL,
  "tipo_atendimento" varchar(30) NOT NULL,
  CONSTRAINT chk_tipo_atendimento CHECK ("tipo_atendimento" IN ('triagem', 'consulta', 'exame'))
);

CREATE TABLE "TRIAGEM" (
  "id_atendimento" integer PRIMARY KEY,
  "cpf_enfermeiro" varchar(11) NOT NULL,
  "queixa_principal" text NOT NULL,
  "frequencia_respiratoria" decimal(5,2),
  "frequencia_cardiaca" decimal(5,2),
  "temperatura" decimal(4,2) NOT NULL,
  "pressao_sistolica" integer,
  "pressao_diastolica" integer,
  "alergias" text,
  "glicemia" decimal(5,2),
  CONSTRAINT chk_temperatura CHECK ("temperatura" > 0),
  CONSTRAINT chk_pressao CHECK (
    ("pressao_sistolica" IS NULL AND "pressao_diastolica" IS NULL) OR
    ("pressao_sistolica" IS NOT NULL AND "pressao_diastolica" IS NOT NULL)
  )
);

CREATE TABLE "CONSULTA" (
  "id_atendimento" integer PRIMARY KEY,
  "cpf_medico" varchar(11) NOT NULL,
  "id_triagem" integer,
  "anamnese" text NOT NULL,
  "diagnostico" text,
  "cid" varchar(10),
  "anotacoes" text
);

CREATE TABLE "EXAME" (
  "id_atendimento" integer PRIMARY KEY,
  "cpf_tecnico_radiologia" varchar(11) NOT NULL,
  "id_consulta" integer,
  "tipo_exame" varchar(100) NOT NULL,
  "observacoes" text,
  "resultado_url" varchar(500),
  "cpf_medico_interno" varchar(11),
  "medico_externo" varchar(100),
  "crm_externo" varchar(20),
  CONSTRAINT chk_medico_solicitante CHECK (
    (
      "cpf_medico_interno" IS NOT NULL AND 
      "medico_externo" IS NULL AND 
      "crm_externo" IS NULL
    ) OR (
      "cpf_medico_interno" IS NULL AND 
      "medico_externo" IS NOT NULL AND 
      "crm_externo" IS NOT NULL
    )
  )
);

CREATE TABLE "DOCUMENTO" (
  "id_documento" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_consulta" integer NOT NULL,
  "cpf_medico" varchar(11) NOT NULL,
  "tipo_documento" varchar(20) NOT NULL,
  "data_emissao" date NOT NULL,
  CONSTRAINT chk_tipo_documento CHECK ("tipo_documento" IN ('atestado', 'prescricao', 'laudo'))
);

CREATE TABLE "ATESTADO" (
  "id_documento" integer PRIMARY KEY,
  "data_inicio" date NOT NULL,
  "data_fim" date NOT NULL,
  "texto" text NOT NULL,
  "cid_atestado" varchar(10),
  CONSTRAINT chk_periodo_atestado CHECK ("data_fim" >= "data_inicio")
);

CREATE TABLE "PRESCRICAO" (
  "id_documento" integer PRIMARY KEY,
  "lista_medicamentos" text NOT NULL,
  "instrucoes" text NOT NULL
);

CREATE TABLE "LAUDO" (
  "id_documento" integer PRIMARY KEY,
  "cid_laudo" varchar(10),
  "conclusao" text NOT NULL
);

CREATE TABLE "PRONTUARIO" (
  "id_prontuario" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_paciente" integer,
  "data_criacao" date NOT NULL,
  "historico_clinico" text,
  "alergias" text,
  "medicacoes_uso_continuo" text,
  "observacoes" text,
  "data_ultima_atualizacao" date,
  "cpf_ultimo_responsavel" varchar(11)
);

CREATE TABLE "ATUALIZACAO_PRONTUARIO" (
  "id_atualizacao" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_paciente" integer NOT NULL,
  "id_atendimento" integer NOT NULL,
  "data_atualizacao" timestamp NOT NULL,
  "cpf_responsavel" varchar(11) NOT NULL,
  "alteracoes_realizadas" text
);

-- Índices
CREATE UNIQUE INDEX idx_pessoa_cpf ON "PESSOA" ("cpf");
CREATE UNIQUE INDEX idx_item_agendamento_servico ON "ITEM" ("id_agendamento", "id_servico");

-- Comentários
COMMENT ON COLUMN "PESSOA"."cpf" IS 'CPF único do indivíduo';
COMMENT ON COLUMN "COBERTURA"."tipo_cobertura" IS 'total ou parcial';
COMMENT ON COLUMN "AGENDAMENTO"."status_agendamento" IS 'agendado, confirmado, cancelado, realizado';
COMMENT ON COLUMN "AGENDAMENTO"."tipo_agendamento" IS 'triagem, consulta, exame';
COMMENT ON COLUMN "AGENDAMENTO"."status_pagamento" IS 'pendente, pago, parcial';
COMMENT ON TABLE "ITEM" IS 'valor_total é calculado: valor_paciente + valor_convenio';
COMMENT ON COLUMN "ATENDIMENTO"."tipo_atendimento" IS 'triagem, consulta, exame';
COMMENT ON TABLE "EXAME" IS 'Constraint implementada: Apenas UM tipo de médico deve ser informado - interno (cpf_medico_interno) OU externo (medico_externo + crm_externo), nunca ambos';
COMMENT ON COLUMN "EXAME"."cpf_medico_interno" IS 'Médico solicitante da clínica';
COMMENT ON COLUMN "EXAME"."medico_externo" IS 'Nome do médico externo';
COMMENT ON COLUMN "EXAME"."crm_externo" IS 'CRM do médico externo';
COMMENT ON COLUMN "DOCUMENTO"."tipo_documento" IS 'atestado, prescricao, laudo';

-- Foreign Keys
ALTER TABLE "TELEFONE_PESSOA" ADD FOREIGN KEY ("cpf") REFERENCES "PESSOA" ("cpf");
ALTER TABLE "EMAIL_PESSOA" ADD FOREIGN KEY ("cpf") REFERENCES "PESSOA" ("cpf");
ALTER TABLE "ADMINISTRADOR" ADD FOREIGN KEY ("cpf") REFERENCES "PESSOA" ("cpf");
ALTER TABLE "PACIENTE" ADD FOREIGN KEY ("cpf") REFERENCES "PESSOA" ("cpf");
ALTER TABLE "FUNCIONARIO" ADD FOREIGN KEY ("cpf") REFERENCES "PESSOA" ("cpf");
ALTER TABLE "ENFERMEIRO" ADD FOREIGN KEY ("cpf") REFERENCES "FUNCIONARIO" ("cpf");
ALTER TABLE "MEDICO" ADD FOREIGN KEY ("cpf") REFERENCES "FUNCIONARIO" ("cpf");
ALTER TABLE "TEC_RADIOLOGIA" ADD FOREIGN KEY ("cpf") REFERENCES "FUNCIONARIO" ("cpf");
ALTER TABLE "CLINICA" ADD FOREIGN KEY ("cpf_administrador") REFERENCES "ADMINISTRADOR" ("cpf");
ALTER TABLE "TELEFONE_CLINICA" ADD FOREIGN KEY ("id_clinica") REFERENCES "CLINICA" ("id_clinica");
ALTER TABLE "EMAIL_CLINICA" ADD FOREIGN KEY ("id_clinica") REFERENCES "CLINICA" ("id_clinica");
ALTER TABLE "CLINICA_PESSOA" ADD FOREIGN KEY ("id_clinica") REFERENCES "CLINICA" ("id_clinica");
ALTER TABLE "CLINICA_PESSOA" ADD FOREIGN KEY ("cpf") REFERENCES "PESSOA" ("cpf");
ALTER TABLE "CLINICA_PESSOA" ADD FOREIGN KEY ("cpf_responsavel_cadastro") REFERENCES "FUNCIONARIO" ("cpf");
ALTER TABLE "COBERTURA" ADD FOREIGN KEY ("id_convenio") REFERENCES "CONVENIO" ("id_convenio");
ALTER TABLE "COBERTURA" ADD FOREIGN KEY ("id_servico") REFERENCES "SERVICO" ("id_servico");
ALTER TABLE "VINCULO" ADD FOREIGN KEY ("id_paciente") REFERENCES "PACIENTE" ("id_paciente");
ALTER TABLE "VINCULO" ADD FOREIGN KEY ("id_convenio") REFERENCES "CONVENIO" ("id_convenio");
ALTER TABLE "AGENDAMENTO" ADD FOREIGN KEY ("id_paciente") REFERENCES "PACIENTE" ("id_paciente");
ALTER TABLE "AGENDAMENTO" ADD FOREIGN KEY ("cpf_funcionario") REFERENCES "FUNCIONARIO" ("cpf");
ALTER TABLE "AGENDAMENTO" ADD FOREIGN KEY ("id_clinica") REFERENCES "CLINICA" ("id_clinica");
ALTER TABLE "AGENDAMENTO" ADD FOREIGN KEY ("id_convenio") REFERENCES "CONVENIO" ("id_convenio");
ALTER TABLE "ITEM" ADD FOREIGN KEY ("id_agendamento") REFERENCES "AGENDAMENTO" ("id_agendamento");
ALTER TABLE "ITEM" ADD FOREIGN KEY ("id_servico") REFERENCES "SERVICO" ("id_servico");
ALTER TABLE "ATENDIMENTO" ADD FOREIGN KEY ("id_agendamento") REFERENCES "AGENDAMENTO" ("id_agendamento");
ALTER TABLE "ATENDIMENTO" ADD FOREIGN KEY ("id_paciente") REFERENCES "PACIENTE" ("id_paciente");
ALTER TABLE "TRIAGEM" ADD FOREIGN KEY ("id_atendimento") REFERENCES "ATENDIMENTO" ("id_atendimento");
ALTER TABLE "TRIAGEM" ADD FOREIGN KEY ("cpf_enfermeiro") REFERENCES "ENFERMEIRO" ("cpf");
ALTER TABLE "CONSULTA" ADD FOREIGN KEY ("id_atendimento") REFERENCES "ATENDIMENTO" ("id_atendimento");
ALTER TABLE "CONSULTA" ADD FOREIGN KEY ("cpf_medico") REFERENCES "MEDICO" ("cpf");
ALTER TABLE "CONSULTA" ADD FOREIGN KEY ("id_triagem") REFERENCES "TRIAGEM" ("id_atendimento");
ALTER TABLE "EXAME" ADD FOREIGN KEY ("id_atendimento") REFERENCES "ATENDIMENTO" ("id_atendimento");
ALTER TABLE "EXAME" ADD FOREIGN KEY ("cpf_tecnico_radiologia") REFERENCES "TEC_RADIOLOGIA" ("cpf");
ALTER TABLE "EXAME" ADD FOREIGN KEY ("id_consulta") REFERENCES "CONSULTA" ("id_atendimento");
ALTER TABLE "EXAME" ADD FOREIGN KEY ("cpf_medico_interno") REFERENCES "MEDICO" ("cpf");
ALTER TABLE "DOCUMENTO" ADD FOREIGN KEY ("id_consulta") REFERENCES "CONSULTA" ("id_atendimento");
ALTER TABLE "DOCUMENTO" ADD FOREIGN KEY ("cpf_medico") REFERENCES "MEDICO" ("cpf");
ALTER TABLE "ATESTADO" ADD FOREIGN KEY ("id_documento") REFERENCES "DOCUMENTO" ("id_documento");
ALTER TABLE "PRESCRICAO" ADD FOREIGN KEY ("id_documento") REFERENCES "DOCUMENTO" ("id_documento");
ALTER TABLE "LAUDO" ADD FOREIGN KEY ("id_documento") REFERENCES "DOCUMENTO" ("id_documento");
ALTER TABLE "PRONTUARIO" ADD FOREIGN KEY ("id_paciente") REFERENCES "PACIENTE" ("id_paciente");
ALTER TABLE "PRONTUARIO" ADD FOREIGN KEY ("cpf_ultimo_responsavel") REFERENCES "FUNCIONARIO" ("cpf");
ALTER TABLE "ATUALIZACAO_PRONTUARIO" ADD FOREIGN KEY ("id_paciente") REFERENCES "PRONTUARIO" ("id_paciente");
ALTER TABLE "ATUALIZACAO_PRONTUARIO" ADD FOREIGN KEY ("id_atendimento") REFERENCES "CONSULTA" ("id_atendimento");
ALTER TABLE "ATUALIZACAO_PRONTUARIO" ADD FOREIGN KEY ("cpf_responsavel") REFERENCES "MEDICO" ("cpf");